const CHINESE_ITEM_NAMES = Object.freeze({
  oak_log: '橡木原木',
  spruce_log: '云杉原木',
  birch_log: '白桦原木',
  jungle_log: '丛林原木',
  acacia_log: '金合欢原木',
  dark_oak_log: '深色橡木原木',
  mangrove_log: '红树原木',
  cherry_log: '樱花原木',
  stripped_oak_log: '去皮橡木原木',
  stripped_spruce_log: '去皮云杉原木',
  stripped_birch_log: '去皮白桦原木',
  stripped_jungle_log: '去皮丛林原木',
  stripped_acacia_log: '去皮金合欢原木',
  stripped_dark_oak_log: '去皮深色橡木原木',
  stripped_mangrove_log: '去皮红树原木',
  stripped_cherry_log: '去皮樱花原木',
  oak_planks: '橡木木板',
  spruce_planks: '云杉木板',
  birch_planks: '白桦木板',
  jungle_planks: '丛林木板',
  acacia_planks: '金合欢木板',
  dark_oak_planks: '深色橡木木板',
  mangrove_planks: '红树木板',
  cherry_planks: '樱花木板',
  wooden_pickaxe: '木镐',
  stone_pickaxe: '石镐',
  iron_pickaxe: '铁镐',
  diamond_pickaxe: '钻石镐',
  netherite_pickaxe: '下界合金镐',
  wooden_axe: '木斧',
  stone_axe: '石斧',
  iron_axe: '铁斧',
  diamond_axe: '钻石斧',
  netherite_axe: '下界合金斧',
  wooden_shovel: '木铲',
  stone_shovel: '石铲',
  iron_shovel: '铁铲',
  diamond_shovel: '钻石铲',
  netherite_shovel: '下界合金铲',
  wooden_sword: '木剑',
  stone_sword: '石剑',
  iron_sword: '铁剑',
  diamond_sword: '钻石剑',
  netherite_sword: '下界合金剑',
  leather_helmet: '皮革帽子',
  leather_chestplate: '皮革上衣',
  leather_leggings: '皮革裤子',
  leather_boots: '皮革靴子',
  chainmail_helmet: '锁链头盔',
  chainmail_chestplate: '锁链胸甲',
  chainmail_leggings: '锁链护腿',
  chainmail_boots: '锁链靴子',
  iron_helmet: '铁头盔',
  iron_chestplate: '铁胸甲',
  iron_leggings: '铁护腿',
  iron_boots: '铁靴子',
  golden_helmet: '金头盔',
  golden_chestplate: '金胸甲',
  golden_leggings: '金护腿',
  golden_boots: '金靴子',
  diamond_helmet: '钻石头盔',
  diamond_chestplate: '钻石胸甲',
  diamond_leggings: '钻石护腿',
  diamond_boots: '钻石靴子',
  bread: '面包',
  apple: '苹果',
  golden_apple: '金苹果',
  enchanted_golden_apple: '附魔金苹果',
  cooked_beef: '熟牛排',
  beef: '生牛肉',
  cooked_porkchop: '熟猪排',
  porkchop: '生猪排',
  cooked_chicken: '熟鸡肉',
  chicken: '生鸡肉',
  cooked_mutton: '熟羊肉',
  mutton: '生羊肉',
  baked_potato: '烤马铃薯',
  carrot: '胡萝卜',
  wheat: '小麦',
  wheat_seeds: '小麦种子',
  torch: '火把',
  stick: '木棍',
  chest: '箱子',
  crafting_table: '工作台',
  furnace: '熔炉',
  blast_furnace: '高炉',
  smoker: '烟熏炉',
  coal: '煤炭',
  charcoal: '木炭',
  iron_ingot: '铁锭',
  raw_iron: '粗铁',
  gold_ingot: '金锭',
  raw_gold: '粗金',
  copper_ingot: '铜锭',
  raw_copper: '粗铜',
  diamond: '钻石',
  cobblestone: '圆石',
  stone: '石头',
  sand: '沙子',
  glass: '玻璃',
  dirt: '泥土',
  wooden_hoe: '木锄',
  stone_hoe: '石锄',
  iron_hoe: '铁锄',
  diamond_hoe: '钻石锄',
  netherite_hoe: '下界合金锄',
  golden_hoe: '金锄',
  golden_pickaxe: '金镐',
  golden_axe: '金斧',
  golden_shovel: '金铲',
  golden_sword: '金剑',
  arrow: '箭',
  bone: '骨头',
  egg: '鸡蛋',
  glow_ink_sac: '荧光墨囊',
  gunpowder: '火药',
  lantern: '灯笼',
  music_disc_far: '音乐唱片 Far',
  oak_sapling: '橡树树苗',
  acacia_sapling: '金合欢树苗',
  phantom_membrane: '幻翼膜',
  rotten_flesh: '腐肉',
  string: '线',
  sugar: '糖',
  coal_ore: '煤矿石',
  deepslate_coal_ore: '深层煤矿石',
  iron_ore: '铁矿石',
  deepslate_iron_ore: '深层铁矿石',
  copper_ore: '铜矿石',
  deepslate_copper_ore: '深层铜矿石',
  diamond_ore: '钻石矿石',
  deepslate_diamond_ore: '深层钻石矿石',
  gold_ore: '金矿石',
  deepslate_gold_ore: '深层金矿石',
  redstone_ore: '红石矿石',
  deepslate_redstone_ore: '深层红石矿石',
  lapis_ore: '青金石矿石',
  deepslate_lapis_ore: '深层青金石矿石'
})

function getChineseItemName(itemName) {
  const name = typeof itemName === 'string' ? itemName : itemName?.name
  if (!name) return ''
  return CHINESE_ITEM_NAMES[name] || name
}

function formatItemDisplayName(item) {
  return getChineseItemName(item?.name || item)
}

module.exports = {
  CHINESE_ITEM_NAMES,
  formatItemDisplayName,
  getChineseItemName
}
